// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf8IMTY2aOKzzk7mTlzm4MnJPnkcsRZW0',
    appId: '1:489513630876:web:8f7a9bd133214053f68159',
    messagingSenderId: '489513630876',
    projectId: 'here-and-there-33632',
    authDomain: 'here-and-there-33632.firebaseapp.com',
    storageBucket: 'here-and-there-33632.appspot.com',
    measurementId: 'G-NG1PE985K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeVLl9SgOnilwasYYLqtXi1yrD0DG3TW4',
    appId: '1:489513630876:android:54faa779aa42ea75f68159',
    messagingSenderId: '489513630876',
    projectId: 'here-and-there-33632',
    storageBucket: 'here-and-there-33632.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYoB9vxU8Pi1SHW8iFbETojJNRg3RyOgY',
    appId: '1:489513630876:ios:a55fecdfa9214733f68159',
    messagingSenderId: '489513630876',
    projectId: 'here-and-there-33632',
    storageBucket: 'here-and-there-33632.appspot.com',
    iosBundleId: 'com.example.hereAndThere',
  );
}
